### ISSUE TITLE
The folder "reconstruct_this" is missing

### ISSUE THREAD

**Issue by hshbnian** [OmarPadierna/3DReconstruction#5]
As it is mentioned in the readme file, it should be a folder called "reconstrcut_this" inside of the "Reconstruction" folder. Without this folder, there would not be any pair of images to open!!!

**Comment by huzhoudiao** [comment]
So what should we do

**Comment by OmarPadierna** [comment]
As referenced in the tutorial, the point of this code is for you to do reconstruction with your own images. 

This means that you will have to: 1) Calibrate your own camera, 2) take two pictures with that camera, create a folder called 3) "reconstruct_this" and store your two pictures in there. If you follow the tutorial referenced in the readme you should be able to reconstruct your own pictures.

**Comment by hshbnian** [comment]
Dear Omar,

Thank you for your response!
That is true. However, the point is we want to obtain and see the same demonstrated and reported 3D reconstructed results first, then apply it to our data and calibrated information of our own. Unfortunately, I could not be able to get a good reconstructed result using this tutorial and my own calibrated data.
Thank you.
________________________________
